### ISSUE TITLE
Slug is set to null when use term with non-ascii string

### ISSUE THREAD

**Issue by kittipongint** [Lecturize/Laravel-Taxonomies#10]
I made a code like this -> $post->addTerm(['English','ภาษาไทย'], 'article_category');

[Table terms]
id     name        slug
============
1     English      english
2     ภาษาไทย   NULL

**Comment by AlexanderPoellmann** [comment]
That seems to be related to `cviebrock/eloquent-sluggable`, have you looked into their docs?
