### ISSUE TITLE
Problem when assigning existing term to more taxonomies

### ISSUE THREAD

**Issue by michal-simoncic** [Lecturize/Laravel-Taxonomies#11]
I found problem, when I had 2 taxonomies for example 1. hair color, 2. eyes color and was trying to assign for example black color to both taxonomies. If term (black) wasn't exist before, everything worked. But if term already exists, it will assign only first taxonomy, no matter if it's the right one.

I fixed function addTerm() in file: 
lecturize\laravel-taxonomies\src\Traits\HasTaxonomies.php

` $tax = Taxonomy::where('term_id', $term)->where('taxonomy', $taxonomy)->first();`

I think there was missing : ->where('taxonomy', $taxonomy)

so function addTerm is now : 

```
public function addTerm($terms, $taxonomy, $parent = 0, $order = 0) {
        $terms = TaxableUtils::makeTermsArray($terms);

        $this->createTaxables($terms, $taxonomy, $parent, $order);

        $terms = Term::whereIn('name', $terms)->pluck('id')->all();
        print_r($terms);


        if (count($terms) > 0) {
            foreach ($terms as $term) {
                if ($this->taxonomies()->where('taxonomy', $taxonomy)->where('term_id', $term)->first())
                    continue;
                $tax = Taxonomy::where('term_id', $term)->where('taxonomy', $taxonomy)->first();
                $this->taxonomies()->attach($tax->id);
            }
            return;
        }

        $this->taxonomies()->detach();
    }
```

**Comment by AlexanderPoellmann** [comment]
Should be fixed in v1.0.1, thank you for the report! Please be aware of the renamed methods etc. in this new release version.
