### ISSUE TITLE
Laravel 8 compatibility

### ISSUE THREAD

**Issue by martinsnajdr** [Lecturize/Laravel-Taxonomies#13]
Hello,

I see in description it says "for Laravel 5", but is there a problem to make it Laravel 8 compatible? Trying to install it via composer, but always getting an error because of the cviebrock/eloquent-sluggable version (8 for Laravel 8)

Thanks.

**Comment by AlexanderPoellmann** [comment]
I am looking into this over the next few days, but please feel free to submit a PR in the meantime!
