### ISSUE TITLE
Error when migration php artisan

### ISSUE THREAD

**Issue by mehrshaddarzi** [Lecturize/Laravel-Taxonomies#15]
Please Check:

![rewrwer](https://user-images.githubusercontent.com/949491/121800049-d945ba00-cc44-11eb-911a-9dd3a1ff0221.JPG)

**Comment by sonnxx** [comment]
I also have the same problem.

using:
- Laravel Framework 8.47.0
- PHP 7.4.20 (cli)

**Comment by sonnxx** [comment]
> Please Check:
> 
> ![rewrwer](https://user-images.githubusercontent.com/949491/121800049-d945ba00-cc44-11eb-911a-9dd3a1ff0221.JPG)

Check the namespace, if your PSR-4 namespace won't match the class file location you will likely get that error. Run composer dump-autoload afterwards to be on a save side.

If not work and you can.

`php artisan make:migration extendToxonomiesTable`

A file in the database  folder will be initialized. And you can copy code at file old to new file. 
**Remember to keep an eye on Classname**

run command final 
`php artisan migrate --path={{path-new-file-migration}}`

**Comment by AlexanderPoellmann** [comment]
My bad, fixed this in the latest commit.
