### ISSUE TITLE
Custom Taxonomy model, or add method

### ISSUE THREAD

**Issue by fgilio** [Lecturize/Laravel-Taxonomies#3]
Hello!

Is there a way to use a custom Taxonomy model or just add a method to it?
I need a custom morphedByMany relation, like you show on line 43 with the "An example for a related posts model".

In the end, what I need to do is get a list of terms which have been associated to some other model. I managed to do it like this:
```php
$tags = Term::has('taxonomies.posts')->select('name')->pluck('name')->all();
```
But, of course I then need that posts morphedByMany relation. Is maintaining a fork it the only way?

--
Thanks for this great package, it's exactly what I was looking for.
F

**Comment by AlexanderPoellmann** [comment]
You would simply 

```
<?php namespace App\Models;

use Lecturize\Taxonomies\Models\Taxonomy as TaxonomyBase;

class Taxonomy extends TaxonomyBase
{
    // add your custom relation here
}
```

**Comment by fgilio** [comment]
Yes! I understood little about the inner workings at the time of that question...
Thank you for the response 👍🏻

**Comment by AlexanderPoellmann** [comment]
You're welcome! Sorry for the late reply anyways 👍
