### ISSUE TITLE
sluggable error on fresh install

### ISSUE THREAD

**Issue by abdullahahci** [Lecturize/Laravel-Taxonomies#6]
Sluggable needs '/config/sluggable.php' config file,
So in fresh install when trying to add new term laravel gives error:

> array_merge(): Argument #1 is not an array
> in SlugService.php (line 65)

P.S.: Please add info in your Readme file for usage of 'HasTaxonomies' trait, as a starter I barely figured it out

**Comment by AlexanderPoellmann** [comment]
I've updated the readme, thanks for pointing that out!
